### ISSUE TITLE
Import-VroResourceElement upload plain text resources as "application/octet-stream" content type

### ISSUE THREAD

**Issue by cjchacon** [jakkulabs/PowervRO#11]
Steps to reproduce
------------------
```powershell
$category = Get-vROCategory -CategoryType 'ResourceElementCategory' | ogv -PassThru
echo echo "{`n`t`"Names`": [`n`t`t`"Chacón`",`n`t`t`"Es-Es`",`n`t`t`"Está`"`n`t]`n}" > example.json
Import-vROResourceElement -CategoryId $category.ID -File .\example.json -Verbose -Debug -Confirm:$false
```
![imagen](https://user-images.githubusercontent.com/2378321/38736000-d68e4976-3f2a-11e8-9be7-04dee27d2e1c.png)

Expected behavior
-----------------
Plain text resources should be uploaded as "text/plain".

Actual behavior
---------------
Plain text files are uploaded as "application/octet-stream"

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.15063.502
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.15063.502
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $vROConnection
Server             : https://pcloudportal:443
Username           : x
EncodedPassword    : x
Version            : 7.3.0.5481809
APIVersion         : 5.5.2
SignedCertificates : True
SslProtocol        : Tls12
```

**Comment by jonathanmedd** [comment]
I've tested this and it's the same behaviour in the vRO client, i.e. if you import the file in your example, it's imported as "application/octet-stream". It appears to be related to the file extension because if you import a file with a *.txt extension, either with the vRO client or PowervRO, it is imported as "text/plain".

There does not appear to be anything within the API to alter this at import time. However, it is possible to alter it via vRO post import - I have documented that previously here: https://www.jonathanmedd.net/2016/10/change-the-mime-type-of-a-vro-resource-element.html
